name: lue_tutorial
channels:
  - conda-forge
  - nodefaults
dependencies:
  - docopt
  - gdal
  - imageio
  - matplotlib
  - lue==0.3.10
  # - rasterio  # 20250812: Conda reports conflicts, only needed for postprocessing
