name: lue_tutorial
channels:
- https://lue.computationalgeography.org/download/conda
- conda-forge
- nodefaults
dependencies:
- docopt
- gdal
- imageio
- ipython  # Optional
- matplotlib
- lue>0.3.7
- rasterio
