name: Linux

on:
  push:
    branches: [ "main" ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash -l {0}

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v4

      - uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-version: latest
          auto-update-conda: true
          conda-solver: "libmamba"
          python-version: 3.12

      - name: setup platform
        run: |
          conda env create --file=environment/configuration/conda_environment.yml
          conda activate lue_tutorial
          export LD_PRELOAD=$(find $CONDA_PREFIX -name libtcmalloc_minimal.so.4)
          python -c "import lue; print(lue.__version__)"

      - name: game_of_life
        run: |
          conda activate lue_tutorial
          export LD_PRELOAD=$(find $CONDA_PREFIX -name libtcmalloc_minimal.so.4)

          cd use_case/game_of_life
          python game_of_life.py 5000 1000 10 generation
          ls -l *.tif

      - name: usle
        run: |
          source "${HOME}/conda/etc/profile.d/conda.sh"
          conda activate lue_tutorial

          wget https://lue.computationalgeography.org/download/lue_qa/elevation.tif
          python usle.py 1000 elevation.tif usle.tif
          ls -l *.tif
