name: Windows

on:
  push:
    branches: [ "main" ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: "windows-2022"

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v4

      - uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-version: latest
          auto-update-conda: true
          conda-solver: "libmamba"
          python-version: 3.12

      - name: setup platform
        run: |
          conda env create --file=environment/configuration/conda_environment.yml
          conda activate lue_tutorial
          python -c "import lue; print(lue.__version__)"
